### ISSUE TITLE
Upload progress bar and placeholder picture

### ISSUE THREAD

**Issue by J77J** [choonkeat/attache_client#11]
Should the placeholder picture and progress bar work by default if I install this gem? I ask as I have installed it and cannot seem to get the placeholder picture to show nor the progress bar (uploads work, but not the above). Any pointers as to how this can be acheived?

**Comment by choonkeat** [comment]
Yes, they should work like https://attache-demo.herokuapp.com/

Did you [install `react-rails` gem](https://github.com/reactjs/react-rails#installation) or include [react and react-dom scripts](https://facebook.github.io/react/downloads.html#individual-downloads) in your layout?

**Comment by J77J** [comment]
I installed the react-rails gem, yes. I'm using bourbon rather than bootstrap, but I don't think it's to do with that as I installed bootstrap to test and that made no difference, so I went back to bourbon.

**Comment by J77J** [comment]
Very strange - just shifted
//= require attache
to the bottom of application.js directly above //=require_tree and now the placeholder and progress bar show, so it appears this works as it should.. My apologies, thanks Choon.

**Comment by choonkeat** [comment]
:clap:
