### ISSUE TITLE
Is turbolinks stopping this from working correctly?

### ISSUE THREAD

**Issue by J77J** [choonkeat/attache_client#12]
When navigating directly to the file upload page in a browser(copy and pasting the url) I get the correct page, with placeholder and upload progress bar etc, however, if I navigate to it from a link on my site there is no placeholder nor is there a progress bar on upload. This is resolved if I refresh the page.

It also works correctly if I remove turbolinks(to test - this isn't really an option for me).

I have tried adding the jquery-turbolinks gem but this doesn't seem to work either. I'm stumped as it seems to work fine in the demo...

Any ideas?

**Comment by choonkeat** [comment]
Are you using turbolinks 5 beta? It changed from `page:change` event to something else - I'll need to add that support

**Comment by choonkeat** [comment]
https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js :sob:

**Comment by J77J** [comment]
Ugh. Thanks. I had been looking at attache-rails and turbolinks. I hadn't even thought to look at react-rails. I'll update this later, and report back, but it looks like this is likely the problem.. Thanks Choon.

**Comment by choonkeat** [comment]
Might need a bigger fix, looking at how comprehensive react-rails ujs is...

**Comment by J77J** [comment]
OK, I have updated react-rails to 1.6.2, but no joy I'm afraid. The behaviour is the same as before...
(nb - I am using turbolinks 5.0.0.beta2, and rails 5.0.0.beta3)

**Comment by choonkeat** [comment]
@J77J using `react-rails` is not required. i've fixed up `attache-rails` to also listen for `turbolinks:load` (which is turbolinks 5 event). should work now

**Comment by J77J** [comment]
Thanks Choon! It's working well now (although if I try to remove react-rails gem it falls to bits) Am I missing something here? Not really too important as its working now which is the main thing! :)

**Comment by choonkeat** [comment]
If you remove `react-rails` gem, then you'd need to include react by other means

e.g. inside your `app/views/layouts/application`, _before_ the line `javascript_include_tag  'application'` you can include [the 2 script tags provided by fb](https://facebook.github.io/react/downloads.html#react-15.0.1-production)
