### ISSUE TITLE
AttacheRails.upgrade_fileinputs doesn't exist

### ISSUE THREAD

**Issue by shawnonthenet** [choonkeat/attache_client#15]
The documentation recommends using AttacheRails.upgrade_fileinputs but that function doesn't exist in the code anymore.

**Comment by choonkeat** [comment]
oops, looks like i forgot to export it. let me know if `fix/export-upgradeFileInput` branch works for you? 535775d

**Comment by shawnonthenet** [comment]
Yup that did it thanks for the quick response.  

An image server is something I've been meaning to do myself for my projects for ages so I really appreciate the project.

**Comment by choonkeat** [comment]
> Yup that did it thanks for the quick response.

thanks for verifying, i've released v3.0.2

> something I've been meaning to do myself for my projects

when you do, make a [compatible server](https://github.com/choonkeat/attache#readme) then we all benefit 👏
