### ISSUE TITLE
exclude certain file types

### ISSUE THREAD

**Issue by J77J** [choonkeat/attache_client#18]
Is there a method to exclude/include certain file types for upload?

ie disallow upload of pdf or gif etc

I'm sure I saw somewhere with details on how to do this with attache - but for the life of me i can now no longer find it?

thanks,

Johnny

**Comment by choonkeat** [comment]
You can have your html markup limit to certain file types

``` html
<input accept=".png"/>
```

**Comment by J77J** [comment]
Hmm, why did I think this was a function within attache rails?.. anyway,

thanks again,

J.

**Comment by choonkeat** [comment]
Alternatively, you can perform validation on the JSON attribute (e.g. filename, content_type) and reject accordingly
