### ISSUE TITLE
Coffee Script?

### ISSUE THREAD

**Issue by flyfy1** [choonkeat/attache_client#7]
Just a quick check, are you using CoffeeScript for `AttacheCORSUpload.js`? The code is so clean & beautiful and I think it is compiled from CoffeeScript.

I'm trying to migrate this project into a purely front-end solution, and I think it would be helpful if I can see the original coffee script.

**Comment by choonkeat** [comment]
You're probably right that it was originally written in CoffeeScript, but not by me. I just adopted it for here; probably from stackoverflow or some gist. If I recall the original reference, I'll put a note there

**Comment by choonkeat** [comment]
FYI @flyfy1 the new source is https://github.com/choonkeat/attache-rails/blob/master/src/javascripts/attache/cors_upload.js
